Test test

diff --git a/run-cucumber b/run-cucumber
--- a/run-cucumber
+++ b/run-cucumber
@@ -1,5 +1,12 @@
 #!/bin/bash
-mv .env .env.old
+if [ $# -eq 0 ]
+  then
+    echo "Continuing execution even if command fails..."
+  else
+    set -ev
+    echo "Running in travis mode..."
+fi
+[ -f .env ] && mv .env .env.old || echo Skipping .env backup
 echo "COOKIE_SECRET=insert-random-string" >> .env
 echo "TWILIO_ACCOUNT_SID=add-twilio-sid-here" >> .env
 echo "TWILIO_AUTH_TOKEN=add-auth-token-here" >> .env
@@ -22,5 +29,5 @@ sleep 5
 ./node_modules/.bin/cucumber-js
 pkill node
 rm .env
-PGPASSWORD=postgres psql -c "DROP DATABASE courtbotat" -h localhost -U postgres
-mv .env.old .env
+psql -c "DROP DATABASE courtbotat" -h localhost -U postgres
+[ -f .env.old ] && mv .env.old .env || echo Skipping .env restore
